apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: m.gatien@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: management-b.pomelo.health
  namespace: default
spec:
  secretName: management-b-tls
  issuerRef:
    name: letsencrypt
  commonName: management-b.pomelo.health
  dnsNames:
    - "*.management-b.pomelo.health"