apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: default
  project: default
  source: https://github.com/jetstack/cert-manager
    path: deploy/charts/cert-manager
    chart: jetstack/cert-manager
    helm:
      values: |
        installCRDs: true

    repoURL: https://charts.jetstack.io
    targetRevision: 1.3.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
      - ApplyOutOfSyncOnly=true
